"""add StudentPeriod table

Revision ID: 0119449915bc
Revises: 0121f8a608f6
Create Date: 2024-09-15 17:35:22.396316

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "0119449915bc"
down_revision: Union[str, None] = "0121f8a608f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Get the current database inspector
    inspector = sa.inspect(op.get_bind())
    table_names = inspector.get_table_names()

    if "student_periods" not in table_names:
        op.create_table(
            "student_periods",
            sa.Column("period_id", sa.String(), nullable=False),
            sa.Column("student_id", sa.Integer(), nullable=False),
            sa.ForeignKeyConstraint(
                ["period_id"],
                ["periods.id"],
            ),
            sa.ForeignKeyConstraint(
                ["student_id"],
                ["users.id"],
            ),
            sa.PrimaryKeyConstraint("period_id", "student_id"),
        )

    # ---------- init student_periods table ----------
    connection = op.get_bind()
    connection.execute(
        sa.text(
            "INSERT INTO student_periods (period_id, student_id) "
            "SELECT :period_id, id FROM users WHERE role = 'STUDENT' "
            "ON CONFLICT (period_id, student_id) DO NOTHING"
        ),
        {"period_id": "2C2024"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("student_periods")
    # ### end Alembic commands ###
