"""add project states in Period

Revision ID: 0121f8a608f6
Revises: e3751539bc5b
Create Date: 2024-09-11 23:07:12.955885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0121f8a608f6"
down_revision: Union[str, None] = "e3751539bc5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "periods", sa.Column("initial_project_active", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "periods", sa.Column("intermediate_project_active", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "periods", sa.Column("final_project_active", sa.Boolean(), nullable=True)
    )

    # update existing periods
    op.execute(
        "UPDATE periods SET initial_project_active = False WHERE initial_project_active IS NULL"
    )
    op.execute(
        "UPDATE periods SET intermediate_project_active = False WHERE intermediate_project_active IS NULL"
    )
    op.execute(
        "UPDATE periods SET final_project_active = False WHERE final_project_active IS NULL"
    )

    # modify columns so they don't allow null values
    op.alter_column(
        "periods", "initial_project_active", existing_type=sa.Boolean(), nullable=False
    )
    op.alter_column(
        "periods",
        "intermediate_project_active",
        existing_type=sa.Boolean(),
        nullable=False,
    )
    op.alter_column(
        "periods", "final_project_active", existing_type=sa.Boolean(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("periods", "final_project_active")
    op.drop_column("periods", "intermediate_project_active")
    op.drop_column("periods", "initial_project_active")
    # ### end Alembic commands ###
