"""Add titles columns and dates

Revision ID: 0c6a1e2f4bdb
Revises: 0b1dfc0ed206
Create Date: 2024-10-01 19:19:55.611772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c6a1e2f4bdb'
down_revision: Union[str, None] = '0b1dfc0ed206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('pre_report_title', sa.String(length=100), nullable=True))
    op.add_column('groups', sa.Column('final_report_title', sa.String(length=100), nullable=True))
    op.add_column('groups', sa.Column('final_report_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('groups', 'final_report_date')
    op.drop_column('groups', 'final_report_title')
    op.drop_column('groups', 'pre_report_title')
    # ### end Alembic commands ###
