"""add dates table

Revision ID: 140c542d2c01
Revises: feccbed960a7
Create Date: 2024-10-08 20:15:38.545190

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "140c542d2c01"
down_revision: Union[str, None] = "feccbed960a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dates_slots",
        sa.Column("period_id", sa.String(), nullable=False),
        sa.Column("slot", sa.DateTime(), nullable=False, primary_key=True),
        sa.ForeignKeyConstraint(["period_id"], ["periods.id"], ondelete="CASCADE"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dates_slots")
    # ### end Alembic commands ###
