"""add columns to dates tables

Revision ID: 6b37846cb4de
Revises: 972e5ddd861b
Create Date: 2024-10-26 17:04:43.827095

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6b37846cb4de"
down_revision: Union[str, None] = "972e5ddd861b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dates_slots", sa.Column("assigned", sa.Boolean(), nullable=True))
    op.add_column(
        "tutors_dates_slots", sa.Column("assigned", sa.Boolean(), nullable=True)
    )
    op.add_column(
        "tutors_dates_slots",
        sa.Column("tutor_or_evaluator", sa.String(), nullable=True),
    )

    # Como ya tenemos data hay que pasarla a False
    op.execute("UPDATE dates_slots SET assigned = true WHERE assigned IS NULL")
    op.execute("UPDATE tutors_dates_slots SET assigned = true WHERE assigned IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tutors_dates_slots", "tutor_or_evaluator")
    op.drop_column("tutors_dates_slots", "assigned")
    op.drop_column("dates_slots", "assigned")
    # ### end Alembic commands ###
