"""add intermediate field

Revision ID: 972e5ddd861b
Revises: 7d0c0baebc8e
Create Date: 2024-10-10 14:59:07.541767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "972e5ddd861b"
down_revision: Union[str, None] = "7d0c0baebc8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "groups",
        sa.Column("intermediate_assigment", sa.String(length=250), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("groups", "intermediate_assigment")
    # ### end Alembic commands ###
