"""Add period_id column to groups table

Revision ID: c41806b65098
Revises: 069cdd65470b
Create Date: 2024-09-08 20:34:51.113580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c41806b65098'
down_revision: Union[str, None] = '069cdd65470b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('period_id', sa.String(), nullable=False))
    op.create_foreign_key(
        'fk_groups_period_id', # fk name
        'groups', # table that contains fk
        'periods', # reference table
        ['period_id'], # groups table column
        ['id'] # periods table column
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_groups_period_id', 'groups', type_='foreignkey')
    op.drop_column('groups', 'period_id')
    # ### end Alembic commands ###

