"""add period_id in Groups

Revision ID: e3751539bc5b
Revises: 069cdd65470b
Create Date: 2024-09-10 22:10:14.852340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3751539bc5b'
down_revision: Union[str, None] = '069cdd65470b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('period_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'groups', 'periods', ['period_id'], ['id'])
    
    # update existing groups
    op.execute("UPDATE groups SET period_id = '2C2024' WHERE period_id IS NULL")

    # modify column so it doesn't allow null values
    op.alter_column('groups', 'period_id', existing_type=sa.String(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='foreignkey')
    op.drop_column('groups', 'period_id')
    # ### end Alembic commands ###
