"""Add column reviewer id

Revision ID: feccbed960a7
Revises: 0c6a1e2f4bdb
Create Date: 2024-10-04 17:14:39.966539

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "feccbed960a7"
down_revision: Union[str, None] = "0c6a1e2f4bdb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("groups", sa.Column("reviewer_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "groups", "users", ["reviewer_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "groups", type_="foreignkey")
    op.drop_column("groups", "reviewer_id")
    # ### end Alembic commands ###
